CREATE TABLE `telemetry_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `IMEI` bigint(20) unsigned NOT NULL,
  `reqType` varchar(2) CHARACTER SET latin1 NOT NULL,
  `numPage` int(10) unsigned NOT NULL,
  `Code` smallint(5) unsigned NOT NULL,
  `Module1GSM` tinyint(3) unsigned NOT NULL,
  `Module1USB` tinyint(3) unsigned NOT NULL,
  `Module1Watch` tinyint(3) unsigned NOT NULL,
  `Module1SIM` tinyint(3) unsigned NOT NULL,
  `Module1Network` tinyint(3) unsigned NOT NULL,
  `Module1Roaming` tinyint(3) unsigned NOT NULL,
  `Module1Engine` tinyint(3) unsigned NOT NULL,
  `Time` int(10) unsigned NOT NULL,
  `GSM` tinyint(3) unsigned NOT NULL,
  `LastTime` int(10) unsigned NOT NULL,
  `Lat` int(11) NOT NULL,
  `Lon` int(11) NOT NULL,
  `Alt` int(11) NOT NULL,
  `Course` smallint(5) unsigned NOT NULL,
  `Mileage` float NOT NULL,
  `CAN_EngineTurns` smallint(5) unsigned NOT NULL,
  `CAN_Temp` tinyint(4) NOT NULL,
  `CAN_EngineLoad` tinyint(3) unsigned NOT NULL,
  `CAN_Speed` tinyint(3) unsigned NOT NULL,
  `CAN_AxleLoad1` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `CAN_AxleLoad2` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `CAN_AxleLoad3` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `CAN_AxleLoad4` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `CAN_AxleLoad5` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `StateU_Ain1` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `StateU_Ain2` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `StateU_Ain3` smallint(5) unsigned NOT NULL,
  `StateU_Ain4` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `StateU_Ain5` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `StateInImp1` int(10) unsigned DEFAULT NULL,
  `StateInImp2` int(10) unsigned DEFAULT NULL,
  `Temp1` tinyint(1) DEFAULT -128,
  `Temp2` tinyint(1) DEFAULT -128,
  `Temp3` tinyint(4) DEFAULT -128,
  `Speed` float DEFAULT NULL,
  `Frequency1` smallint(5) unsigned DEFAULT NULL,
  `Motochas` int(10) unsigned DEFAULT NULL,
  `Power` smallint(5) unsigned DEFAULT NULL,
  `Reserv` smallint(5) unsigned DEFAULT NULL,
  `ATemp16` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp15` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp14` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp13` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp12` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp11` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp10` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp9` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp8` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp7` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp6` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp5` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp4` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp3` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp2` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `ATemp1` smallint(5) unsigned NOT NULL DEFAULT 65535,
  `patched` enum('YES','NO') NOT NULL DEFAULT 'YES',
  PRIMARY KEY (`id`),
  KEY `IMEI_Time` (`IMEI`,`Time`),
  KEY `IMEI` (`IMEI`),
  KEY `IMEI_numPage` (`IMEI`,`numPage`),
  KEY `Time` (`Time`)
) ENGINE=InnoDB AUTO_INCREMENT=79303497 DEFAULT CHARSET=utf8;
