#!/usr/bin/php

<?php

const USER = 'ftp';

if (!defined('SLASH')) {
    if (strtoupper(substr(PHP_OS, 0, 3)) == 'WIN') {
        define('SLASH', '\\');
    } else {
        define('SLASH', '/');
    }
}

function status()
{
    sleep(1);
    if (file_exists(__DIR__ . SLASH . 'run.lock')) {
        $file_pid = file_get_contents(__DIR__ . SLASH . 'run.lock');
        $ps = shell_exec('ps -A | grep ' . $file_pid);
        if (!is_null($ps)) {
            return 'Сервер NTCB запущен' . "\n";
        }
        return 'Сервер NTCB остановлен' . "\n";
    } else {
        return 'Сервер NTCB остановлен' . "\n";
    }
}

function stop()
{
    if (file_exists(__DIR__ . SLASH . 'run.lock'))
    {
        $file_pid = file_get_contents(__DIR__ . SLASH . 'run.lock');
        $ps = shell_exec('ps -A | grep ' . $file_pid);
        if (!is_null($ps))
        {
            shell_exec('kill ' . $file_pid);
        }
    }
}

function start($port = 9000)
{
    shell_exec('sudo -u ' . USER . ' nohup php ' . __DIR__ . SLASH . 'start.php ' . $port . ' >> /dev/null &');
}

if ($argc < 2)
{
    die("Неизвестная команда. Допустимые команды: start [port], stop, reload [port], status, update\n");
}

$port = 9000;

if (isset($argv[2]) && is_numeric($argv[2]))
{
    $port = $argv[2];
}

switch ($argv[1]) {
    case 'start':
        start($port);
        echo status();
        break;
    case 'stop':
        stop();
        echo status();
        break;
    case 'status':
        echo status();
        break;
    case 'reload':
        stop();
        echo status();
        start($port);
        echo status();
        break;
    case 'update':
        echo shell_exec('cd ' . __DIR__ . SLASH . ' && sudo -u ' . USER . ' git pull');
        echo shell_exec('cd ' . __DIR__ . SLASH . ' && sudo -u ' . USER . ' composer install');
        echo shell_exec('cd ' . __DIR__ . SLASH . ' && sudo -u ' . USER . ' composer update');
        break;
    default:
        echo "Неизвестная команда. Допустимые команды: start [port], stop, reload [port], status, update\n";
}