#!/usr/bin/php

<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

function status()
{
    sleep(1);
    if (file_exists(__DIR__ . DIRECTORY_SEPARATOR . 'run.lock')) {
        $file_pid = file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'run.lock');
        $ps = shell_exec('ps -A | grep ' . $file_pid);
        if (!is_null($ps)) {
            return 'Сервер NTCB запущен' . "\n";
        }
        return 'Сервер NTCB остановлен' . "\n";
    } else {
        return 'Сервер NTCB остановлен' . "\n";
    }
}

function stop()
{
    if (file_exists(__DIR__ . DIRECTORY_SEPARATOR . 'run.lock'))
    {
        $file_pid = file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'run.lock');
        $ps = shell_exec('ps -A | grep ' . $file_pid);
        if (!is_null($ps))
        {
            shell_exec('kill ' . $file_pid);
        }
    }
}

function start($port = 9000)
{
    $dotenv = new Dotenv\Dotenv(__DIR__);
    $dotenv->load();

    shell_exec('sudo -u ' . $_ENV['LINUX_RUN_USER'] . ' nohup php ' . __DIR__ . DIRECTORY_SEPARATOR . 'start.php ' . $port . ' >> /dev/null &');
}

if ($argc < 2)
{
    die("Неизвестная команда. Допустимые команды: start [port], stop, reload [port], status, update\n");
}

$port = 9000;

if (isset($argv[2]) && is_numeric($argv[2]))
{
    $port = $argv[2];
}

switch ($argv[1]) {
    case 'start':
        start($port);
        echo status();
        break;
    case 'stop':
        stop();
        echo status();
        break;
    case 'status':
        echo status();
        break;
    case 'reload':
        stop();
        echo status();
        start($port);
        echo status();
        break;
    default:
        echo "Неизвестная команда. Допустимые команды: start [port], stop, reload [port], status, update\n";
}